# Generated by Django 3.2.9 on 2021-12-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='is_leader',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(choices=[('entrada oficina', 'ENTRADA OFICINA'), ('entrada homeofice', 'ENTRADA HOMEOFICE'), ('salida oficina', 'SALIDA OFICINA'), ('salida homeofice', 'SALIDA HOMEOFICE')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
