# Generated by Django 3.2.9 on 2021-11-17 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20211109_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 16, 22, 1, 299388)),
        ),
    ]
