# Generated by Django 3.2.9 on 2021-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_boolean_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='telefono',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='telefono_casa',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
