# Generated by Django 3.2.8 on 2022-01-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_numero_nounico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Archivos Psicologicos/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
        migrations.CreateModel(
            name='DatosMedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(max_length=250, null=True)),
                ('peso', models.CharField(max_length=250, null=True)),
                ('estatura', models.CharField(max_length=250, null=True)),
                ('alergias', models.CharField(max_length=500, null=True)),
                ('sangre', models.CharField(max_length=250, null=True)),
                ('enfermedad', models.CharField(max_length=300, null=True)),
                ('lentes', models.CharField(max_length=250, null=True)),
                ('fumas', models.CharField(max_length=250, null=True)),
                ('tomas', models.CharField(max_length=250, null=True)),
                ('deporte', models.CharField(max_length=250, null=True)),
                ('sueño', models.CharField(max_length=250, null=True)),
                ('covid', models.CharField(max_length=250, null=True)),
                ('vacuna', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
