# Generated by Django 3.1.2 on 2021-09-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
