# Generated by Django 3.1.2 on 2021-09-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_delete_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
