# Generated by Django 3.1.2 on 2022-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_docslegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
