# Generated by Django 3.1.2 on 2021-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=250, null=True, unique=True),
        ),
    ]
