# Generated by Django 3.1.2 on 2021-09-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacto_emergencia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='departamento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='egreso',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ingreso',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nacimiento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono_casa',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono_emergencia',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
