# Generated by Django 3.2.10 on 2022-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_boleanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
