# Generated by Django 3.1.2 on 2021-09-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20210928_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='puesto',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
