# Generated by Django 3.2.10 on 2022-06-09 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_nombreenpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaisen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Actas Kaisen/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
    ]
