# Generated by Django 3.1.2 on 2021-09-28 17:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_profile_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=250, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
