# Generated by Django 3.2.10 on 2022-07-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_kaisen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hat', models.CharField(max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
