# Generated by Django 3.2.10 on 2022-07-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_hat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
