# Generated by Django 3.2.10 on 2022-07-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0012_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoslegales',
            options={'ordering': ['-dateTimeOfUpload'], 'verbose_name_plural': 'Documentos Legales'},
        ),
        migrations.AlterModelOptions(
            name='documentosmedicos',
            options={'ordering': ['-dateTimeOfUpload'], 'verbose_name_plural': 'Documentos Medicos'},
        ),
        migrations.AlterModelOptions(
            name='justificantesmedicos',
            options={'ordering': ['-dateTimeOfUpload'], 'verbose_name_plural': 'Justificantes Medicos'},
        ),
        migrations.AlterModelOptions(
            name='kaisen',
            options={'ordering': ['-dateTimeOfUpload'], 'verbose_name_plural': 'kaizen'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Entradas/Salidas'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name_plural': 'Relaciones'},
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('A Tiempo', 'A Tiempo'), ('Retardo', 'Retardo')], default=True, null=True),
        ),
        migrations.CreateModel(
            name='AsignacionHat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hats', to='social.hat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
