# Generated by Django 3.2.10 on 2022-07-14 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0013_auto_20220714_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades', models.CharField(max_length=500, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actividades', to='social.hat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
