# Generated by Django 3.2.10 on 2022-07-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_actividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='user',
        ),
        migrations.AlterField(
            model_name='actividades',
            name='hat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='social.hat'),
        ),
    ]
