# Generated by Django 3.1.2 on 2021-09-29 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20210929_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
