# Generated by Django 3.1.2 on 2021-09-30 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_auto_20210929_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post1',
            options={'ordering': ['-timestamp1']},
        ),
        migrations.RemoveField(
            model_name='post1',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='post1',
            name='timestamp1',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 10, 55, 8, 122899)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 10, 55, 8, 122899)),
        ),
    ]
