# Generated by Django 3.2.10 on 2022-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_mymodel_timestampeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Fecha',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='entrada',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
