# Generated by Django 3.1.2 on 2021-09-30 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_auto_20210930_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post1',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='post1',
            name='timestamp1',
        ),
        migrations.AddField(
            model_name='post1',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 11, 28, 78448)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 11, 28, 74385)),
        ),
    ]
