# Generated by Django 3.2.10 on 2022-11-14 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0018_documentacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-dateTimeOfUpload'], 'verbose_name_plural': 'Documentos Psicologicos'},
        ),
        migrations.AlterModelOptions(
            name='documentacion',
            options={'ordering': ['-dateTimeOfUpload'], 'verbose_name_plural': 'Documentos Personales'},
        ),
        migrations.AlterModelOptions(
            name='egresos',
            options={'verbose_name_plural': 'Salida empresa'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name_plural': 'Informacion Personal'},
        ),
        migrations.CreateModel(
            name='CredentialToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
