# Generated by Django 3.1.2 on 2021-09-30 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_auto_20210930_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='content1',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post1',
            old_name='user1',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 35, 11, 903816)),
        ),
        migrations.AlterField(
            model_name='post1',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 35, 11, 903816)),
        ),
    ]
