# Generated by Django 3.1.2 on 2021-09-30 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0019_auto_20210930_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 51, 16, 197805))),
                ('content', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_entrada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PostSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_salida', models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 51, 16, 197805))),
                ('content_salida', models.TextField()),
                ('user_salida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_salida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp_salida'],
            },
        ),
        migrations.RemoveField(
            model_name='post1',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
