# Generated by Django 3.2.10 on 2023-01-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_auto_20221114_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='contratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAspirante', models.CharField(max_length=200)),
                ('uploadedNotes', models.FileField(upload_to='Notas/')),
                ('uploadedCV', models.FileField(upload_to='CV/')),
                ('is_contratado', models.BooleanField(default=False, null=True)),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Documentos contratacion',
                'ordering': ['-dateTimeOfUpload'],
            },
        ),
    ]
