# Generated by Django 3.1.2 on 2021-09-30 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_auto_20210930_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentrada',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 12, 4, 41, 174344)),
        ),
        migrations.AlterField(
            model_name='postsalida',
            name='timestamp_salida',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 12, 4, 41, 175343)),
        ),
    ]
