# Generated by Django 3.2.10 on 2023-01-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_contratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='comentarios',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
