# Generated by Django 3.1.2 on 2021-09-30 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_auto_20210930_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentrada',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 12, 16, 27, 540263)),
        ),
        migrations.AlterField(
            model_name='postsalida',
            name='timestamp_salida',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 12, 16, 27, 541261)),
        ),
    ]
