# Generated by Django 3.2.10 on 2023-10-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_contratacion_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresos',
            name='egreso',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='egresos',
            name='ingreso',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
