# Generated by Django 3.2.10 on 2023-10-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_auto_20231012_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresos',
            name='egreso',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='egresos',
            name='ingreso',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
