# Generated by Django 3.1.2 on 2021-09-30 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20210930_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp_entrada',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 22, 0, 5, 694602, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post1',
            name='timestamp_salida',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 22, 0, 5, 694602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 17, 0, 5, 694602)),
        ),
        migrations.AlterField(
            model_name='post1',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 17, 0, 5, 694602)),
        ),
    ]
