# Generated by Django 3.1.2 on 2021-09-30 22:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20210930_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 17, 1, 1, 66444)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post1',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 17, 1, 1, 67444)),
        ),
        migrations.AlterField(
            model_name='post1',
            name='timestamp_salida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
