# Generated by Django 3.1.2 on 2021-09-30 22:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_auto_20210930_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 17, 16, 49, 831376)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp_entrada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post1',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 17, 16, 49, 831376)),
        ),
        migrations.AlterField(
            model_name='post1',
            name='timestamp_salida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
