# Generated by Django 3.1.2 on 2021-10-02 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_auto_20210930_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp_entrada',
        ),
        migrations.RemoveField(
            model_name='post1',
            name='timestamp_salida',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 23, 28, 0, 353896)),
        ),
        migrations.AlterField(
            model_name='post1',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 23, 28, 0, 353896)),
        ),
    ]
